[package]
name = "rust-sc2"
version = "0.4.0"
authors = ["Armageddon <lunyx1337@gmail.com>"]
edition = "2018"

[dependencies]
sc2-proto = { git = "https://github.com/UltraMachine/sc2-proto-rs.git" }
sc2-macro = { path = "sc2-macro" }
tungstenite = "^0.10.1"
url = "^2.1.1"
protobuf = "^2.10.2"
ndarray = "^0.13.0"
num-traits = "^0.2.11"
num-derive = "^0.3.0"
regex = "^1.3.6"
dirs = "^2.0.2"
itertools = "^0.9.0"
lazy_static = "^1.4.0"

[dev-dependencies]
rand = "^0.7.3"
clap = "^2.33.0"

[[example]]
name = "worker-rush"

[[example]]
name = "reaper-rush"

[[example]]
name = "zerg-rush"
