[package]
name = "rust-sc2"
version = "0.1.0"
authors = ["Armageddon <lunyx1337@gmail.com>"]
edition = "2018"

[dependencies]
sc2-proto = { git = "https://github.com/UltraMachine/sc2-proto-rs.git" }
sc2-macro = { path = "sc2-macro" }
tokio = { version = "^0.2.13", features = ["full"] }
tokio-tungstenite = "^0.10.1"
tungstenite = "^0.10.1"
futures-util = "0.3.4"
url = "^2.1.1"
protobuf = "^2.10.2"
ndarray = "^0.13.0"
num-traits = "^0.2.11"
num-derive = "^0.3.0"
regex = "^1.3.6"
dirs = "^2.0.2"
# pbr = "^1.0.2"
# lazy_static = "^1.4.0"
