[package]
name = "rust-sc2"
version = "0.5.1"
authors = ["Armageddon <lunyx1337@gmail.com>"]
edition = "2018"

[dependencies]
sc2-proto = { git = "https://github.com/UltraMachine/sc2-proto-rs.git" }
sc2-macro = { path = "sc2-macro" }
tungstenite = "^0.10.1"
url = "^2.1.1"
protobuf = "^2.14.0"
ndarray = "^0.13.0"
num-traits = "^0.2.11"
num-derive = "^0.3.0"
regex = "^1.3.7"
dirs = "^2.0.2"
itertools = "^0.9.0"
lazy_static = "^1.4.0"
maplit = "^1.0.2"
rand = "^0.7.3"
log = "^0.4.8"

[dev-dependencies]
clap = "^2.33.0"
