[package]
name = "sc2-proc-macro"
version = "0.6.0"
authors = ["Armageddon <lunyx1337@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^1.0.17", features = ["full"] }
quote = "^1.0.3"
proc-macro2 = "^1.0.9"
regex = "^1.3.7"
